#
# Copyright 2023 Sly Technologies Inc. All Rights Reserved.
#
# 1. Copying, modification, and distribution of this file, or executable
# versions of this file, is governed by the terms of the Sly Technologies Software
# license agreement under which this file was made available. If you do not
# agree to the terms of the license do not install, copy, access or
# otherwise use this file.
#
# 2. Under the Sly Technologies Software license agreement you are granted a
# limited, non-exclusive, non-assignable, copyright license to copy, modify
# and distribute this file in conjunction with Sly Technologies software
# supplied by Sly Technologies Inc.
#
# 3. The full Sly Technologies Software license agreement is included in this
# distribution, please see LICENSE text file
#
# 4. Redistributions of source code must retain this copyright notice,
# list of conditions and the following disclaimer.
#
# THIS SOFTWARE IS PROVIDED "AS IS" WITHOUT ANY WARRANTIES, EXPRESS OR
# IMPLIED, AND Sly Technologies DISCLAIMS ALL IMPLIED WARRANTIES INCLUDING ANY
# IMPLIED WARRANTY OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, OR OF
# FITNESS FOR A PARTICULAR PURPOSE. TO THE EXTENT NOT PROHIBITED BY
# APPLICABLE LAW, IN NO EVENT SHALL Sly Technologies BE LIABLE FOR PERSONAL INJURY,
# OR ANY INCIDENTAL, SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES WHATSOEVER,
# INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOSS OF PROFITS, CORRUPTION OR
# LOSS OF DATA, FAILURE TO TRANSMIT OR RECEIVE ANY DATA OR INFORMATION,
# BUSINESS INTERRUPTION OR ANY OTHER COMMERCIAL DAMAGES OR LOSSES, ARISING
# OUT OF OR RELATED TO YOUR USE OR INABILITY TO USE Sly Technologies SOFTWARE OR
# SERVICES OR ANY THIRD PARTY SOFTWARE OR APPLICATIONS IN CONJUNCTION WITH
# THE Sly Technologies SOFTWARE OR SERVICES, HOWEVER CAUSED, REGARDLESS OF THE THEORY
# OF LIABILITY (CONTRACT, TORT OR OTHERWISE) AND EVEN IF Sly Technologies HAS BEEN
# ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. SOME JURISDICTIONS DO NOT ALLOW
# THE EXCLUSION OR LIMITATION OF LIABILITY FOR PERSONAL INJURY, OR OF
# INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THIS LIMITATION MAY NOT APPLY TO YOU.
#
#


# Extract the Makefile path
MAKEFILE_DIR_PATH := $(abspath $(dir $(lastword $(MAKEFILE_LIST))))

# Set the target name
TARGET := net-capture

SRCS := $(TARGET).c

include $(MAKEFILE_DIR_PATH)/../Makefile.inc
